### ISSUE TITLE
WPF制作带居中三角形指示的Tooltip样式的Tooltip | HPDell的个人博客

### ISSUE THREAD

**Issue by HPDell** [HPDell/HPDell.github.io#2]
https://hpdell.github.io/WPF/WPF-Bootstrap-Tooltip/

**Comment by lopengye** [comment]
Hello, 我有个问题想问，就是Tooltip在相对鼠标的位置的问题。。
当控件靠近屏幕边缘时，鼠标放上去，就会出现Tooltip偏离很远的问题；
当控件靠近下边缘时，Tooltip箭头指向的位置又不对了。。

**Comment by HPDell** [comment]
抱歉~这个问题我还没试过，我当时的需求的位置都在屏幕中间。我再测试看看吧
